import type { PropertyModel } from "@/store/slices/properties/types";
import { v4 as uuid } from "uuid";

export const initialState: PropertyModel[] = [
  {
    id: uuid(),
    name: "The Gilded Hourglass",
    description: "A luxury boutique hotel with a vintage, old-world theme.",
    location: "The Enclave, Port Silver",
    type: ["hotel"],
    facilities: ["free-wifi", "fitness-center", "spa", "parking"],
    rating: 5,
    reviewScore: 8.2,
    reviewsCount: 2539,
    price: {
      adult: 300,
      child: 100,
    },
    imageUrl: "/properties/image-a.webp",
  },
  {
    id: uuid(),
    name: "Aether & Ivy",
    description:
      "A chic, modern hotel blending natural elements with sleek design.",
    location: "The Laneways, Castelle",
    type: ["hotel"],
    facilities: ["free-wifi", "fitness-center", "spa", "parking", "restaurant"],
    rating: 5,
    reviewScore: 9.2,
    reviewsCount: 1520,
    price: {
      adult: 400,
      child: 150,
    },
    imageUrl: "/properties/image-b.webp",
  },
  {
    id: uuid(),
    name: "Hotel Monochrome",
    description: "A stylish, minimalist hotel in a bustling city center.",
    location: "Rookridge, Lower Crossford",
    type: ["hotel"],
    facilities: ["free-wifi", "fitness-center", "parking", "restaurant"],
    rating: 4,
    reviewScore: 7.2,
    reviewsCount: 472,
    price: {
      adult: 300,
      child: 120,
    },
    imageUrl: "/properties/image-c.webp",
  },
  {
    id: uuid(),
    name: "The Driftwood Inn",
    description: "A cozy, rustic bed-and-breakfast on a windswept coast.",
    location: "Fallow Heights, Aethelburg",
    type: ["villas"],
    facilities: ["free-wifi", "spa", "parking", "restaurant"],
    rating: 5,
    reviewScore: 8.4,
    reviewsCount: 4217,
    price: {
      adult: 500,
      child: 200,
    },
    imageUrl: "/properties/image-d.webp",
  },
  {
    id: uuid(),
    name: "The Gilded Pheasant",
    description:
      "A classic country house hotel, perfect for a romantic getaway.",
    location: "Millwalk, Old Veridia",
    type: ["hotel"],
    facilities: ["fitness-center", "parking", "restaurant", "kids-playground"],
    rating: 4,
    reviewScore: 8.0,
    reviewsCount: 765,
    price: {
      adult: 200,
      child: 50,
    },
    imageUrl: "/properties/image-e.webp",
  },
  {
    id: uuid(),
    name: "The Solarium",
    description:
      "A trendy, sun-drenched hotel with a focus on wellness and light.",
    location: "The Sonderholm, Kingsmere",
    type: ["hotel"],
    facilities: ["free-wifi", "fitness-center", "spa", "parking", "restaurant"],
    rating: 3,
    reviewScore: 6.2,
    reviewsCount: 124,
    price: {
      adult: 250,
      child: 100,
    },
    imageUrl: "/properties/image-f.webp",
  },
  {
    id: uuid(),
    name: "Seven Stones Lodge",
    description: "A remote, luxury eco-lodge nestled in the mountains.",
    location: "Pebbleford, Raven's Reach",
    type: ["villas"],
    facilities: [
      "free-wifi",
      "fitness-center",
      "spa",
      "parking",
      "restaurant",
      "room-service",
      "kids-playground",
    ],
    rating: 5,
    reviewScore: 7.8,
    reviewsCount: 872,
    price: {
      adult: 320,
      child: 120,
    },
    imageUrl: "/properties/image-g.webp",
  },
  {
    id: uuid(),
    name: "The Velvet Rope",
    description:
      "A glamorous, high-energy hotel known for its rooftop bar and scene.",
    location: "The Glasshouse Quarter, Solstice City",
    type: ["hotel", "apartments"],
    facilities: [
      "free-wifi",
      "fitness-center",
      "spa",
      "parking",
      "restaurant",
      "room-service",
    ],
    rating: 5,
    reviewScore: 9.4,
    reviewsCount: 5218,
    price: {
      adult: 350,
      child: 120,
    },
    imageUrl: "/properties/image-h.webp",
  },
  {
    id: uuid(),
    name: "Nook & Cranny Inn",
    description:
      "A quirky, charming hotel filled with secret passages and unique rooms.",
    location: "Elder Row, Havenrock",
    type: ["hotel", "apartments"],
    facilities: [
      "free-wifi",
      "fitness-center",
      "spa",
      "parking",
      "restaurant",
      "room-service",
    ],
    rating: 4,
    reviewScore: 8.1,
    reviewsCount: 628,
    price: {
      adult: 420,
      child: 150,
    },
    imageUrl: "/properties/image-i.webp",
  },
];
