name: CI
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.6.0
          cache: "npm"

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: Linting
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci